// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvarszcfsujzirbybylz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2YXJzemNmc3VqemlyYnlieWx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMzk2MjgsImV4cCI6MjA2NTgxNTYyOH0.AcJtAKNJYZamZA-sNN_W4iqcHrAY9P3eIbgArpanCRE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);